#!/usr/bin/env bash
# Generate assets/status.js — a gitignored, DERIVED snapshot of real build state
# that index.html reads to keep its dashboard honest. Never committed; regenerated
# by `make status` and automatically after the kernel/check targets.
#
# Runs on the HOST (reads the bind-mounted harness/.build); needs no container.

set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
# shellcheck source=versions.env
source "$HERE/versions.env"

BUILD="$HERE/.build"
BZIMAGE="$BUILD/linux-${KERNEL_VERSION}/arch/x86/boot/bzImage"
CHECKS="$BUILD/.checks"
OUT="$ROOT/assets/status.js"

badge() { printf '{"label":"%s","kind":"%s"}' "$1" "$2"; }   # -> {label,kind}

# scripts: actually run bash -n over every shell script
scripts_label=OK; scripts_kind=ok
for f in "$HERE"/*.sh "$ROOT"/*/check.sh "$ROOT"/wheel/*/check.sh; do
  [ -f "$f" ] || continue
  bash -n "$f" 2>/dev/null || { scripts_label=FAIL; scripts_kind=fail; break; }
done

# foundation: core files present
found_label=OK; found_kind=ok
for f in Dockerfile Makefile harness/versions.env harness/lib.sh; do
  [ -f "$ROOT/$f" ] || { found_label=MISSING; found_kind=fail; break; }
done

# sha pin (drives both the marker and the diagnostics "pinned" badge)
if [ -n "${KERNEL_SHA256:-}" ]; then
  sha_label=OK;      sha_kind=ok;   pin_label=PINNED;   pin_kind=ok
else
  sha_label=PENDING; sha_kind=warn; pin_label=UNPINNED; pin_kind=warn
fi

# kernel build
if [ -f "$BZIMAGE" ]; then ker_label=OK; ker_kind=ok; else ker_label=PENDING; ker_kind=warn; fi

# lessons green: count pass-records written by harness/check.sh
lessons=(01-syscall-is-the-door 02-printk-and-ring-buffer 03-proc-is-code 04-kernel-narrates-itself B1-follow-the-path B2-trace-just-what-matters B3-latency-and-context B4-events-and-histograms H1-gdb-the-live-kernel H2-sysrq-the-panic-button 06-instrument-it-yourself E0-anatomy-of-an-oops 05-the-driver-that-oopses 07-char-device-with-ioctl C1-read-an-oom-report wheel/works-on-my-laptop wheel/mystery-oom-kill wheel/fast-except-sometimes)
pass=0
for l in "${lessons[@]}"; do
  [ -f "$CHECKS/$(echo "$l" | tr / _).pass" ] && pass=$((pass+1))
done
total=${#lessons[@]}
if   [ "$pass" -eq "$total" ]; then les_label=OK;            les_kind=ok
elif [ "$pass" -eq 0 ];        then les_label=PENDING;       les_kind=warn
else                                les_label="${pass}/${total}"; les_kind=warn
fi

# one-line system summary (ASCII only — it lands inside a JS string)
if   [ -z "${KERNEL_SHA256:-}" ] && [ ! -f "$BZIMAGE" ]; then line="phase-1 authored - awaiting sha256 pin + first build"
elif [ ! -f "$BZIMAGE" ];                                then line="sha256 pinned - awaiting first kernel build"
elif [ "$pass" -lt "$total" ];                           then line="kernel built - ${pass}/${total} lesson checks green"
else                                                          line="all systems nominal - ${total}/${total} checks green"
fi

stamp="$(date -u +%Y-%m-%dT%H:%MZ)"

mkdir -p "$ROOT/assets"
cat > "$OUT" <<EOF
// GENERATED by harness/gen-status.sh — do not edit; not committed (gitignored).
// A derived snapshot of real build state on this host. Regenerate: make status
window.KA_STATUS = {
  "generatedAt": "$stamp",
  "statusline": "$line",
  "facts": { "kernel": "$KERNEL_VERSION", "arch": "$GUEST_ARCH" },
  "markers": {
    "foundation": $(badge "$found_label" "$found_kind"),
    "harness":    $(badge OK ok),
    "scripts":    $(badge "$scripts_label" "$scripts_kind"),
    "sha256":     $(badge "$sha_label" "$sha_kind"),
    "kernel":     $(badge "$ker_label" "$ker_kind"),
    "lessons":    $(badge "$les_label" "$les_kind"),
    "pinned":     $(badge "$pin_label" "$pin_kind")
  }
};
EOF
echo "wrote $OUT  ($line)"
