// SPDX-License-Identifier: GPL-2.0
/*
 * proc_window.c — create /proc/kernel-apprentice, backed by a seq_file handler.
 *
 * The point of the lesson: a /proc entry is NOT a file. Each time userspace reads
 * it, the kernel calls ka_show() and that function GENERATES the bytes on the fly.
 * /proc is code wearing a filesystem costume — and here you build the costume.
 *
 * Built out-of-tree against the pinned kernel by ../check.sh, then insmod'd in a
 * QEMU guest. Loading runs ka_init (proc_create); unloading runs ka_exit.
 */
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/proc_fs.h>
#include <linux/seq_file.h>
#include <linux/sched.h>
#include <linux/jiffies.h>

#define PROC_NAME "kernel-apprentice"

/* Called on every read of /proc/kernel-apprentice. The text below is produced
 * here and now — it is not stored anywhere. Read the file twice and the live
 * values (pid, jiffies) change, which is the proof that this is code, not a file. */
static int ka_show(struct seq_file *m, void *v)
{
	seq_printf(m, "kernel-apprentice: hello from a seq_file handler\n");
	seq_printf(m, "generated by kernel code on each read, not stored on disk\n");
	seq_printf(m, "reading process: %s (pid %d)\n", current->comm, task_tgid_vnr(current));
	seq_printf(m, "jiffies now:     %lu\n", jiffies);
	return 0;
}

static int ka_open(struct inode *inode, struct file *file)
{
	return single_open(file, ka_show, NULL);
}

/* Modern kernels (>= 5.6) wire /proc entries with proc_ops, not file_operations. */
static const struct proc_ops ka_proc_ops = {
	.proc_open    = ka_open,
	.proc_read    = seq_read,
	.proc_lseek   = seq_lseek,
	.proc_release = single_release,
};

static struct proc_dir_entry *ka_entry;

static int __init ka_init(void)
{
	ka_entry = proc_create(PROC_NAME, 0444, NULL, &ka_proc_ops);
	if (!ka_entry)
		return -ENOMEM;
	pr_info("kernel-apprentice: /proc/%s created\n", PROC_NAME);
	return 0;
}

static void __exit ka_exit(void)
{
	proc_remove(ka_entry);
	pr_info("kernel-apprentice: /proc/%s removed\n", PROC_NAME);
}

module_init(ka_init);
module_exit(ka_exit);

MODULE_LICENSE("GPL");
MODULE_AUTHOR("kernel-apprentice");
MODULE_DESCRIPTION("Create /proc/kernel-apprentice from a seq_file handler — a window across the boundary.");
